name: Validate Renovate Configuration
on: [ push ]

jobs:
  validate-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Renovate
        run: npm install -g renovate

      - name: Validate Renovate config
        run: npx --yes --package renovate -- renovate-config-validator --strict
