name: Validate Renovate Configuration
on: [ push ]

jobs:
  validate-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install Renovate
        run: npm install -g renovate

      - name: Validate Renovate config
        run: npx --yes --package renovate -- renovate-config-validator --strict
