name: Validate Renovate Configuration
on: [ push ]

jobs:
  validate-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Renovate
        run: npm install -g renovate

      - name: Validate Renovate config
        run: npx --yes --package renovate -- renovate-config-validator --strict
